// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4LLYMcGEsiQfuTeMBrqgY5WsyTjoq8q0',
    appId: '1:221480173389:web:fbf760a05258c241464104',
    messagingSenderId: '221480173389',
    projectId: 'rental-busana',
    authDomain: 'rental-busana.firebaseapp.com',
    storageBucket: 'rental-busana.appspot.com',
    measurementId: 'G-F42M6YBDHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaEC8fpwnr_qsGN2HwwN9x3_EZ3yyuOMs',
    appId: '1:221480173389:android:de72b5f38db281dd464104',
    messagingSenderId: '221480173389',
    projectId: 'rental-busana',
    storageBucket: 'rental-busana.appspot.com',
  );
}
